In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(np.argmax(a))

4

In [2]:
print(np.argmin(a))

0

In [3]:
print(np.where(a>3))

(array([3, 4]),)

In [5]:
print(np.cumsum(a))

[ 1  3  6 10 15]

In [8]:
r=np.random.randint(1,20,1)
print(r)

[5]

In [9]:
r=np.random.randint(1,20,5)
print(r)

[ 3  2  9 13 16]

In [10]:
r=np.random.randint(1,20,20)
print(r)

[17 18  2  4 17 17 18 12  2  1  5 15 12 12  9  4 19  6 12 17]

In [11]:
a=np.array([1,2,3,4,5,6])
b=np.array([3,4,5,6,8,9])
print(np.corrcoef(a,b))

[[1.         0.99216093]
 [0.99216093 1.        ]]

In [13]:
a=np.array([100,99,98,97,96,95])
np.save("ps.npy",a)
print(np.load("ps.npy"))

[100  99  98  97  96  95]

In [14]:
a=np.array([1,2,3,4,5])
print(a[2:])

[3 4 5]

In [15]:
a=np.array([1,2,3,4,5])
print(a[0:-3])

[1 2]

In [21]:
a=np.array([1,2,3,4,5])
print(a[:-1])

[1 2 3 4]

In [17]:
import pandas as sa

In [20]:
z=sa.read_csv("programming_languages.csv")
z

,language,difficulty,popularity,use_cases,year_created,paradigm,typing
0,Python,1,57.9,AI; Data Science; Web Development,1991,Multi-paradigm,Dynamic
1,JavaScript,2,62.3,Web Development; Front-end; Back-end,1995,Multi-paradigm,Dynamic
2,Java,3,30.0,Enterprise; Android; Backend,1995,Object-oriented,Static
3,C++,5,23.5,Game Development; Systems; Embedded,1985,Multi-paradigm,Static
4,C#,3,27.0,Game Development; Desktop; Web,2000,Object-oriented,Static

In [24]:
x=z.loc[1:3,"language":"typing"]
x

,language,difficulty,popularity,use_cases,year_created,paradigm,typing
1,JavaScript,2,62.3,Web Development; Front-end; Back-end,1995,Multi-paradigm,Dynamic
2,Java,3,30.0,Enterprise; Android; Backend,1995,Object-oriented,Static
3,C++,5,23.5,Game Development; Systems; Embedded,1985,Multi-paradigm,Static

In [25]:
x=z.loc[1:3,"language":"year_created"]
x

,language,difficulty,popularity,use_cases,year_created
1,JavaScript,2,62.3,Web Development; Front-end; Back-end,1995
2,Java,3,30.0,Enterprise; Android; Backend,1995
3,C++,5,23.5,Game Development; Systems; Embedded,1985